---
output:
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
    includes:
      # in_header: preamble.tex
      after_body: [biorxiv_2019.09.28figcaps.tex]
    # fig_caption: no
textalign: left  # this does not work...
geometry: margin = 1in
bibliography: paper_references.bib
csl: systematic-biology.csl
link-citations: yes
# indent: true # this works
# header-includes:
#    - \setlength\parindent{24pt}  # this works too, but I'm gonna indent manually with 4 spaces
# nope, 4 spaces indents are not recognized, they do something else
linestretch: 2
header-includes:
    - \usepackage{caption}
    - \usepackage{blindtext}
    - \usepackage[left]{lineno}
    - \linenumbers
  # - \usepackage{xr}
    # - \usepackage[utf8]{inputenc}
    # - \usepackage[english]{babel}
    # - \usepackage[document]{ragged2e}
nocite: |
  @barker2012going, @barker2015new, @burns2014phylogenetics, @claramunt2015new, @gibb2015new, @Hedges2015, @hooper2017chromosomal, @Jetz2012, @price2014niche
---
```{r eval = TRUE, echo = FALSE, warning=FALSE, message=FALSE, results='hide'}
# code to generate the paper data and figures:
# source("data.R")
# inactivated now just for testing purposes
# we are using drake to avoid running the examples everytime we change something in the Rmd and knit
# using this for testing instead:
source("./data/frin_plan.R") # stopped using drake for this, it is better to run the analysis directly
loadd() # loads all the targets listed in the workflow plan of the previous `make()`
library(datelife)
data(opentree_chronograms)
rpackage_available <- FALSE
availability <- ifelse(rpackage_available, "is available", "will be available")
```

``` {r child = 'paper_1-header.Rmd'}
```
\newpage
``` {r child = 'paper_2-abstract.Rmd'}
```
\newpage
\begin{center}
\textsc{Introduction}
\end{center}
``` {r child = 'paper_3-main.Rmd'}
```
\newpage
\begin{center}
\textsc{References}
\end{center}
