---
output:
  bookdown::pdf_document2:
    keep_tex: yes
    toc: false
textalign: left  # this does not work...
geometry: margin = 1in
bibliography: library_red.bib
csl: systematic-biology.csl
link-citations: yes
linestretch: 2
header-includes:
    - \usepackage[left]{lineno}
    - \linenumbers
nocite: |
  @barker2012going, @barker2015new, @burns2014phylogenetics, @claramunt2015new, @gibb2015new, @Hedges2015, @hooper2017chromosomal, @Jetz2012, @price2014niche
---
This information can be used to account for the effect of phylogenetic signal in
studies of trait evolution; to explore potential speciation and extinction dynamics
of interest within a clade; to obtain a time frame of biogeographical events; for
science communication and outreach, amongst others.

Problems and caveats:
`datelife` can be seen as an open resource to know the current state of knowledge on lineage divergence times.
Whether chronograms obtained using this original data can be used reliably to study complicated patterns of evolution is still uncertain.
If all, la facilidad para obtener hipotesis de tiempo de divergencia nos ayudará a evaluar la capacidad de los cronogramas para estudiar otros fenomenos evolutivos.
Por ahora, no podemos aseverar que estos cronogramas puedan usarse para todo tipo de analisis.
