---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ../svm-latex-ms.tex
    # includes:
      # in_header: preamble.tex
      # after_body: [Datelife_paper1_figures_noyaml.tex]
link-citations: yes
bibliography: ../library_red.bib
header-includes:
  - \usepackage{hyperref}
  - \usepackage[left]{lineno}
  - \linenumbers
  - \usepackage{caption}
biblio-style: apsr
title: "DateLife: Leveraging databases and analytical tools to reveal the dated Tree of Life"
thanks: "Replication files are available on the author's Github account (http://github.com/LunaSare). **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding authors**: lsanche7@utk.edu; bomeara@utk.edu; 1. Corresponding adrdress: *Department of Ecology and Evolutionary Biology, University of Tennessee, Knoxville, 425 Hesler Biology Building, Knoxville, TN 37996, USA*"
author:
- name: Luna L. Sanchez Reyes
  affiliation: University of Tennessee, Knoxville
- name: Brian O'Meara
  affiliation: University of Tennessee, Knoxville
abstract: "The combination of new analytical techniques, availability of more fossil and molecular data, and better practices in data sharing has resulted in a steady accumulation of chronograms in public and open databases such as TreeBASE, Dryad, and Open Tree of Life for a large quantity and diversity of organisms in the last few decades. However, getting a tree with branch lengths proportional to time remains difficult for many biologists and the non-academic community, despite its importance in many areas of research, education, and science communication. `datelife` is a service implemented via an R package and a web site (<http://www.datelife.org/>) for efficient reuse, summary and reanalysis of published data on lineage divergence times. The main workflow starts with at least two taxon names as input, either as tip labels on a tree, or as a simple comma separated character string. A name search is then performed across the chronogram database and positively identified source trees are pruned to maintain queried taxa only and stored as a named list of patristic distance matrices. Source chronogram data can be summarised using branch length summary statistics or variance minimizing approaches to generate a single summary chronogram. Source chronogram data can also be used as calibration points to date a tree containing some or all names from the initial query. If there is no information available for any queried taxa, data can be simulated. All source and summary chronograms can be saved in formats that permit easy reuse and reanalysis. Summary and newly generated trees are potentially useful to evaluate evolutionary hypothesis in different areas of research in biology. How well this trees work for this purpose still needs to be tested. `datelife` will be useful to increase awereness on the existing variation in expert time of divergence data, and might foster exploration of the effect of alternative divergence time hypothesis on the results of analyses, nurturing a culture of more cautious interpretation of evolutionary results."
keywords: "Tree; Phylogeny; Scaling; Dating; Ages; Divergence times; Open Science; Congruification; Supertree; Calibrations"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
endnote: no
nocite: |
  @barker2012going, @barker2015new, @burns2014phylogenetics, @claramunt2015new, @gibb2015new, @Hedges2015, @hooper2017chromosomal, @Jetz2012, @price2014niche
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE,
                      message=FALSE, warning=FALSE,
                      fig.path='figs/',
                      cache.path = '_cache/',
                      fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      })
```

``` {r child = '../paper.Rmd'}
```

\newpage

\begin{center}
\textsc{References}
\end{center}

``` {r child = 'paper_figures.Rmd'}
```
